version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0
    executor: ruby/default
    steps:
      - checkout
      - run: sudo gem update --system
      - run: gem install bundler
      - run: bundle install
      - run: rspec spec/controllers/ideas_controller_spec.rb
      - store_artifacts:
          path: coverage/.resultset.json
